// <auto-generated />
namespace CodebasetestMVC_2AfterChanges.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MovieTableCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieTableCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202311140530290_MovieTableCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
